/**
 * useAppActor - PERMANENT REPLACEMENT for useActor in this app.
 *
 * WHY THIS FILE EXISTS:
 * useActor.ts is auto-generated by the Caffeine platform and gets overwritten
 * on every new build with a version that uses useInternetIdentity. This app
 * uses a custom Ed25519 identity stored in identityStore (alias+password login).
 * useInternetIdentity always returns anonymous, so useActor always returns an
 * anonymous actor -- causing login, posting, and admin panel to fail.
 *
 * THIS FILE MUST NOT BE DELETED OR RENAMED.
 * All queries and mutations must import from useAppActor, not from useActor.
 */
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { useEffect } from "react";
import type { backendInterface } from "../backend";
import { createActorWithConfig } from "../config";
import { useIdentityStore } from "../stores/identityStore";
import { getSecretParameter } from "../utils/urlParams";

const APP_ACTOR_QUERY_KEY = "appActor";

export function useAppActor() {
  // Read identity from identityStore (set after alias+password login)
  const identity = useIdentityStore((s) => s.identity);
  const queryClient = useQueryClient();

  const actorQuery = useQuery<backendInterface>({
    queryKey: [
      APP_ACTOR_QUERY_KEY,
      identity?.getPrincipal().toString() ?? "anonymous",
    ],
    queryFn: async () => {
      if (!identity) {
        // Anonymous actor for public reads
        return createActorWithConfig();
      }
      const actor = await createActorWithConfig({
        agentOptions: { identity },
      });
      try {
        const adminToken = getSecretParameter("caffeineAdminToken") ?? "";
        await actor._initializeAccessControlWithSecret(adminToken);
      } catch {
        // Not an admin token -- that's fine
      }
      return actor;
    },
    staleTime: Number.POSITIVE_INFINITY,
    enabled: true,
  });

  // Invalidate all dependent queries when the actor changes
  useEffect(() => {
    if (actorQuery.data) {
      queryClient.invalidateQueries({
        predicate: (query) => !query.queryKey.includes(APP_ACTOR_QUERY_KEY),
      });
    }
  }, [actorQuery.data, queryClient]);

  return {
    actor: actorQuery.data ?? null,
    isFetching: actorQuery.isFetching,
  };
}
