/**
 * NOTE: This file uses useAppActor (NOT useActor) intentionally.
 * useActor.ts is auto-generated by the platform and always returns an anonymous
 * actor. useAppActor reads the Ed25519 identity from identityStore after login.
 * DO NOT replace useAppActor with useActor here.
 *
 * IMPORTANT: Admin write mutations use createActorWithConfig directly from the
 * identity store at mutation time. This ensures a fresh authenticated actor is
 * always used, avoiding stale closures or timing issues with the query cache.
 */
import {
  useMutation,
  useQueries,
  useQuery,
  useQueryClient,
} from "@tanstack/react-query";
import type {
  BlogRole,
  Category,
  CategoryPermission,
  CommentView,
  PostView,
  UserProfile,
} from "../backend.d";
import { createActorWithConfig } from "../config";
import { useIdentityStore } from "../stores/identityStore";
import { useAppActor } from "./useAppActor";

/**
 * Creates a fresh authenticated actor at call time using the current identity.
 * Used for admin write mutations to avoid stale actor issues.
 * Same approach as createAuthenticatedActor in AuthContext (which works reliably).
 */
async function createFreshActorForMutation() {
  const identity = useIdentityStore.getState().identity;
  if (!identity) {
    throw new Error("Inte inloggad – ingen identitet hittad. Logga in igen.");
  }
  console.log(
    "[AdminMutation] Creating fresh actor with principal:",
    identity.getPrincipal().toString(),
  );
  const actor = await createActorWithConfig({ agentOptions: { identity } });
  return actor;
}

export function usePosts() {
  const { actor, isFetching } = useAppActor();
  return useQuery<PostView[]>({
    queryKey: ["posts"],
    queryFn: async () => {
      if (!actor) return [];
      return actor.getPosts();
    },
    enabled: !!actor && !isFetching,
  });
}

export function usePost(postId: string) {
  const { actor, isFetching } = useAppActor();
  return useQuery<PostView | null>({
    queryKey: ["post", postId],
    queryFn: async () => {
      if (!actor) return null;
      return actor.getPost(postId);
    },
    enabled: !!actor && !isFetching && !!postId,
  });
}

export function usePostsByCategory(categoryId: string) {
  const { actor, isFetching } = useAppActor();
  return useQuery<PostView[]>({
    queryKey: ["posts", "category", categoryId],
    queryFn: async () => {
      if (!actor) return [];
      return actor.getPostsByCategory(categoryId);
    },
    enabled: !!actor && !isFetching && !!categoryId,
  });
}

export function useFollowingFeed() {
  const { actor, isFetching } = useAppActor();
  return useQuery<PostView[]>({
    queryKey: ["posts", "following"],
    queryFn: async () => {
      if (!actor) return [];
      return actor.getFollowingFeed();
    },
    enabled: !!actor && !isFetching,
  });
}

export function usePostsByAuthor(authorId: string) {
  const { actor, isFetching } = useAppActor();
  return useQuery<PostView[]>({
    queryKey: ["posts", "author", authorId],
    queryFn: async () => {
      if (!actor || !authorId) return [];
      return actor.getPostsByAuthor(authorId);
    },
    enabled: !!actor && !isFetching && !!authorId,
  });
}

export function useCategories() {
  const { actor, isFetching } = useAppActor();
  return useQuery<Category[]>({
    queryKey: ["categories"],
    queryFn: async () => {
      if (!actor) return [];
      return actor.getCategories();
    },
    enabled: !!actor && !isFetching,
  });
}

/**
 * Returns only the categories that the current user can access:
 * - Categories visible on the homepage (isHidden === false)
 * - Hidden categories where the user has explicit read or comment permissions
 */
export function useAccessibleCategories() {
  const { actor, isFetching } = useAppActor();
  const identity = useIdentityStore((s) => s.identity);
  const principalStr = identity?.getPrincipal().toString() ?? "";

  const categoriesQuery = useQuery<Category[]>({
    queryKey: ["categories"],
    queryFn: async () => {
      if (!actor) return [];
      return actor.getCategories();
    },
    enabled: !!actor && !isFetching,
  });

  const allCategories = categoriesQuery.data ?? [];
  const hiddenCategories = allCategories.filter((c) => c.isHidden);

  const permissionsQueries = useQueries({
    queries: hiddenCategories.map((cat) => ({
      queryKey: ["categoryPermissions", cat.id],
      queryFn: async () => {
        if (!actor) return { readAllowlist: [], commentAllowlist: [] };
        return actor.getCategoryPermissions(cat.id);
      },
      enabled: !!actor && !isFetching,
    })),
  });

  const visibleCategories = allCategories.filter((cat) => {
    if (!cat.isHidden) return true;
    const hiddenIdx = hiddenCategories.findIndex((h) => h.id === cat.id);
    if (hiddenIdx === -1) return false;
    const permResult = permissionsQueries[hiddenIdx];
    if (!permResult?.data) return false;
    const { readAllowlist, commentAllowlist } = permResult.data as {
      readAllowlist: string[];
      commentAllowlist: string[];
    };
    return (
      readAllowlist.includes(principalStr) ||
      commentAllowlist.includes(principalStr)
    );
  });

  return {
    data: visibleCategories,
    isLoading: categoriesQuery.isLoading,
  };
}

export function useComments(postId: string) {
  const { actor, isFetching } = useAppActor();
  return useQuery<CommentView[]>({
    queryKey: ["comments", postId],
    queryFn: async () => {
      if (!actor) return [];
      return actor.getCommentsForPost(postId);
    },
    enabled: !!actor && !isFetching && !!postId,
  });
}

export function useUserProfile(userId: string) {
  const { actor, isFetching } = useAppActor();
  return useQuery<UserProfile | null>({
    queryKey: ["profile", userId],
    queryFn: async () => {
      if (!actor || !userId) return null;
      return actor.getUserProfile(userId);
    },
    enabled: !!actor && !isFetching && !!userId,
  });
}

/** Resolves an authorId (principal string or alias) to a display alias. */
export function useAuthorAlias(authorId: string) {
  const { actor, isFetching } = useAppActor();
  return useQuery<string>({
    queryKey: ["authorAlias", authorId],
    queryFn: async () => {
      if (!actor || !authorId) return authorId;
      try {
        const profile = await actor.getUserProfile(authorId);
        return profile?.alias ?? authorId;
      } catch {
        return authorId;
      }
    },
    enabled: !!actor && !isFetching && !!authorId,
    staleTime: 5 * 60 * 1000,
  });
}

export function useListUsers() {
  const { actor, isFetching } = useAppActor();
  return useQuery<UserProfile[]>({
    queryKey: ["users"],
    queryFn: async () => {
      if (!actor) return [];
      return actor.listUsers();
    },
    enabled: !!actor && !isFetching,
  });
}

export function useFollowers(userId: string) {
  const { actor, isFetching } = useAppActor();
  return useQuery<string[]>({
    queryKey: ["followers", userId],
    queryFn: async () => {
      if (!actor || !userId) return [];
      return actor.getFollowers(userId);
    },
    enabled: !!actor && !isFetching && !!userId,
  });
}

export function useFollowing(userId: string) {
  const { actor, isFetching } = useAppActor();
  return useQuery<string[]>({
    queryKey: ["following", userId],
    queryFn: async () => {
      if (!actor || !userId) return [];
      return actor.getFollowing(userId);
    },
    enabled: !!actor && !isFetching && !!userId,
  });
}

export function useLikePost() {
  const { actor } = useAppActor();
  const qc = useQueryClient();
  return useMutation({
    mutationFn: async ({
      postId,
      liked,
    }: {
      postId: string;
      liked: boolean;
    }) => {
      if (!actor) throw new Error("No actor");
      if (liked) await actor.unlikePost(postId);
      else await actor.likePost(postId);
    },
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ["posts"] });
      qc.invalidateQueries({ queryKey: ["post"] });
    },
  });
}

export function useAddComment() {
  const { actor } = useAppActor();
  const qc = useQueryClient();
  return useMutation({
    mutationFn: async ({
      postId,
      text,
      imageBlob,
    }: {
      postId: string;
      text: string;
      imageBlob: any;
    }) => {
      if (!actor) throw new Error("No actor");
      return actor.addComment(postId, text, imageBlob);
    },
    onSuccess: (_data, vars) => {
      qc.invalidateQueries({ queryKey: ["comments", vars.postId] });
    },
  });
}

export function useDeleteComment() {
  const { actor } = useAppActor();
  const qc = useQueryClient();
  return useMutation({
    mutationFn: async ({
      commentId,
      postId: _postId,
    }: {
      commentId: string;
      postId: string;
    }) => {
      if (!actor) throw new Error("No actor");
      return actor.deleteComment(commentId);
    },
    onSuccess: (_data, vars) => {
      qc.invalidateQueries({ queryKey: ["comments", vars.postId] });
    },
  });
}

export function useLikeComment() {
  const { actor } = useAppActor();
  const qc = useQueryClient();
  return useMutation({
    mutationFn: async ({
      commentId,
      postId: _postId,
    }: {
      commentId: string;
      postId: string;
    }) => {
      if (!actor) throw new Error("No actor");
      return actor.likeComment(commentId);
    },
    onSuccess: (_data, vars) => {
      qc.invalidateQueries({ queryKey: ["comments", vars.postId] });
    },
  });
}

export function useCreatePost() {
  const { actor } = useAppActor();
  const qc = useQueryClient();
  return useMutation({
    mutationFn: async (vars: {
      title: string;
      body: string;
      categoryId: string;
      mediaUrls: any[];
    }) => {
      if (!actor) throw new Error("No actor");
      return actor.createPost(
        vars.title,
        vars.body,
        vars.categoryId,
        vars.mediaUrls,
      );
    },
    onSuccess: () => qc.invalidateQueries({ queryKey: ["posts"] }),
  });
}

export function useEditPost() {
  const { actor } = useAppActor();
  const qc = useQueryClient();
  return useMutation({
    mutationFn: async (vars: {
      postId: string;
      title: string;
      body: string;
      categoryId: string;
      mediaUrls: any[];
    }) => {
      if (!actor) throw new Error("No actor");
      return actor.editPost(
        vars.postId,
        vars.title,
        vars.body,
        vars.categoryId,
        vars.mediaUrls,
      );
    },
    onSuccess: (_data, vars) => {
      qc.invalidateQueries({ queryKey: ["posts"] });
      qc.invalidateQueries({ queryKey: ["post", vars.postId] });
    },
  });
}

export function useDeletePost() {
  const { actor } = useAppActor();
  const qc = useQueryClient();
  return useMutation({
    mutationFn: async (postId: string) => {
      if (!actor) throw new Error("No actor");
      return actor.deletePost(postId);
    },
    onSuccess: () => qc.invalidateQueries({ queryKey: ["posts"] }),
  });
}

export function usePublishPost() {
  const { actor } = useAppActor();
  const qc = useQueryClient();
  return useMutation({
    mutationFn: async (postId: string) => {
      if (!actor) throw new Error("No actor");
      return actor.publishPost(postId);
    },
    onSuccess: () => qc.invalidateQueries({ queryKey: ["posts"] }),
  });
}

export function usePinPost() {
  const { actor } = useAppActor();
  const qc = useQueryClient();
  return useMutation({
    mutationFn: async (postId: string) => {
      if (!actor) throw new Error("No actor");
      return actor.pinPost(postId);
    },
    onSuccess: () => qc.invalidateQueries({ queryKey: ["posts"] }),
  });
}

export function useFollowUser() {
  const { actor } = useAppActor();
  const qc = useQueryClient();
  return useMutation({
    mutationFn: async ({
      targetUserId,
      isFollowing,
    }: {
      targetUserId: string;
      isFollowing: boolean;
    }) => {
      if (!actor) throw new Error("No actor");
      if (isFollowing) await actor.unfollowUser(targetUserId);
      else await actor.followUser(targetUserId);
    },
    onSuccess: (_data, vars) => {
      qc.invalidateQueries({ queryKey: ["followers", vars.targetUserId] });
      qc.invalidateQueries({ queryKey: ["following"] });
    },
  });
}

export function useUpdateUserRole() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: async (vars: { userId: string; newRole: BlogRole }) => {
      const actor = await createFreshActorForMutation();
      return actor.updateUserRole(vars.userId, vars.newRole);
    },
    onSuccess: () => qc.invalidateQueries({ queryKey: ["users"] }),
    onError: (err) =>
      console.error("[AdminMutation] updateUserRole failed:", err),
  });
}

export function useBlockUser() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: async ({
      userId,
      block,
    }: {
      userId: string;
      block: boolean;
    }) => {
      const actor = await createFreshActorForMutation();
      if (block) await actor.blockUser(userId);
      else await actor.unblockUser(userId);
    },
    onSuccess: () => qc.invalidateQueries({ queryKey: ["users"] }),
    onError: (err) => console.error("[AdminMutation] blockUser failed:", err),
  });
}

export function useAdminDeleteUser() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: async (targetUserId: string) => {
      const actor = await createFreshActorForMutation();
      return actor.adminDeleteUser(targetUserId);
    },
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ["users"] });
      qc.invalidateQueries({ queryKey: ["posts"] });
    },
    onError: (err) =>
      console.error("[AdminMutation] adminDeleteUser failed:", err),
  });
}

export function useCategoryPermissions(categoryId: string) {
  const { actor, isFetching } = useAppActor();
  return useQuery<CategoryPermission>({
    queryKey: ["categoryPermissions", categoryId],
    queryFn: async () => {
      if (!actor) return { readAllowlist: [], commentAllowlist: [] };
      return actor.getCategoryPermissions(categoryId);
    },
    enabled: !!actor && !isFetching && !!categoryId,
  });
}

/**
 * Admin write mutations below use createFreshActorForMutation() to always
 * get a fresh authenticated actor at call time. This avoids stale closures
 * and mirrors the approach used in createAuthenticatedActor (login flow).
 */

export function useAddCategory() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: async ({
      name,
      isHidden,
    }: {
      name: string;
      isHidden: boolean;
    }) => {
      const actor = await createFreshActorForMutation();
      return actor.addCategory(name, isHidden);
    },
    onSuccess: () => qc.invalidateQueries({ queryKey: ["categories"] }),
    onError: (err) => console.error("[AdminMutation] addCategory failed:", err),
  });
}

export function useDeleteCategory() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: async (categoryId: string) => {
      const actor = await createFreshActorForMutation();
      return actor.deleteCategory(categoryId);
    },
    onSuccess: () => qc.invalidateQueries({ queryKey: ["categories"] }),
    onError: (err) =>
      console.error("[AdminMutation] deleteCategory failed:", err),
  });
}

export function useSetCategoryPermissions() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: async (vars: {
      categoryId: string;
      readAllowlist: string[];
      commentAllowlist: string[];
    }) => {
      const actor = await createFreshActorForMutation();
      return actor.setCategoryPermissions(
        vars.categoryId,
        vars.readAllowlist,
        vars.commentAllowlist,
      );
    },
    onSuccess: (_data, vars) => {
      qc.invalidateQueries({
        queryKey: ["categoryPermissions", vars.categoryId],
      });
    },
    onError: (err) =>
      console.error("[AdminMutation] setCategoryPermissions failed:", err),
  });
}

export function useSetCategoryVisibility() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: async ({
      categoryId,
      isHidden,
    }: {
      categoryId: string;
      isHidden: boolean;
    }) => {
      const actor = await createFreshActorForMutation();
      return actor.setCategoryVisibility(categoryId, isHidden);
    },
    onSuccess: () => qc.invalidateQueries({ queryKey: ["categories"] }),
    onError: (err) =>
      console.error("[AdminMutation] setCategoryVisibility failed:", err),
  });
}
