/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from "@icp-sdk/core/agent";
import type { IDL } from "@icp-sdk/core/candid";
import type { Principal } from "@icp-sdk/core/principal";

export type BlogRole =
  | { moderator: null }
  | { user: null }
  | { superadmin: null };
export interface Category {
  id: string;
  name: string;
}
export interface CommentView {
  id: string;
  authorId: string;
  createdAt: Time;
  text: string;
  likes: Array<string>;
  imageUrl: [] | [ExternalBlob];
  postId: string;
}
export type ExternalBlob = Uint8Array;
export interface PostView {
  id: string;
  categoryId: string;
  title: string;
  isPublished: boolean;
  authorId: string;
  body: string;
  createdAt: Time;
  likes: Array<string>;
  updatedAt: Time;
  mediaUrls: Array<ExternalBlob>;
  isPinned: boolean;
}
export type Time = bigint;
export interface UserProfile {
  alias: string;
  isBlocked: boolean;
  blogRole: BlogRole;
}
export type UserRole = { admin: null } | { user: null } | { guest: null };
export interface _CaffeineStorageCreateCertificateResult {
  method: string;
  blob_hash: string;
}
export interface _CaffeineStorageRefillInformation {
  proposed_top_up_amount: [] | [bigint];
}
export interface _CaffeineStorageRefillResult {
  success: [] | [boolean];
  topped_up_amount: [] | [bigint];
}
export interface _SERVICE {
  _caffeineStorageBlobIsLive: ActorMethod<[Uint8Array], boolean>;
  _caffeineStorageBlobsToDelete: ActorMethod<[], Array<Uint8Array>>;
  _caffeineStorageConfirmBlobDeletion: ActorMethod<
    [Array<Uint8Array>],
    undefined
  >;
  _caffeineStorageCreateCertificate: ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >;
  _caffeineStorageRefillCashier: ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >;
  _caffeineStorageUpdateGatewayPrincipals: ActorMethod<[], undefined>;
  _initializeAccessControlWithSecret: ActorMethod<[string], undefined>;
  addCategory: ActorMethod<[string], undefined>;
  addComment: ActorMethod<[string, string, [] | [ExternalBlob]], string>;
  assignCallerUserRole: ActorMethod<[Principal, UserRole], undefined>;
  blockUser: ActorMethod<[string], undefined>;
  createPost: ActorMethod<
    [string, string, string, Array<ExternalBlob>],
    string
  >;
  deleteAccount: ActorMethod<[], undefined>;
  deleteCategory: ActorMethod<[string], undefined>;
  deleteComment: ActorMethod<[string], undefined>;
  deletePost: ActorMethod<[string], undefined>;
  editPost: ActorMethod<
    [string, string, string, string, Array<ExternalBlob>],
    undefined
  >;
  followUser: ActorMethod<[string], undefined>;
  getCallerUserProfile: ActorMethod<[], [] | [UserProfile]>;
  getCallerUserRole: ActorMethod<[], UserRole>;
  getCategories: ActorMethod<[], Array<Category>>;
  getCommentsForPost: ActorMethod<[string], Array<CommentView>>;
  getFollowers: ActorMethod<[string], Array<string>>;
  getFollowing: ActorMethod<[string], Array<string>>;
  getFollowingFeed: ActorMethod<[], Array<PostView>>;
  getPost: ActorMethod<[string], [] | [PostView]>;
  getPosts: ActorMethod<[], Array<PostView>>;
  getPostsByAuthor: ActorMethod<[string], Array<PostView>>;
  getPostsByCategory: ActorMethod<[string], Array<PostView>>;
  getProfile: ActorMethod<[], [] | [UserProfile]>;
  getUserProfile: ActorMethod<[string], [] | [UserProfile]>;
  isCallerAdmin: ActorMethod<[], boolean>;
  likeComment: ActorMethod<[string], undefined>;
  likePost: ActorMethod<[string], undefined>;
  listUsers: ActorMethod<[], Array<UserProfile>>;
  login: ActorMethod<[Uint8Array], string>;
  pinPost: ActorMethod<[string], undefined>;
  publishPost: ActorMethod<[string], undefined>;
  register: ActorMethod<[string, Uint8Array, Uint8Array], string>;
  saveCallerUserProfile: ActorMethod<[UserProfile], undefined>;
  unblockUser: ActorMethod<[string], undefined>;
  unfollowUser: ActorMethod<[string], undefined>;
  unlikePost: ActorMethod<[string], undefined>;
  updateUserRole: ActorMethod<[string, BlogRole], undefined>;
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
