/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BlogRole = IDL.Variant({
  'moderator' : IDL.Null,
  'user' : IDL.Null,
  'superadmin' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'alias' : IDL.Text,
  'isBlocked' : IDL.Bool,
  'blogRole' : BlogRole,
});
export const Category = IDL.Record({ 'id' : IDL.Text, 'name' : IDL.Text });
export const Time = IDL.Int;
export const CommentView = IDL.Record({
  'id' : IDL.Text,
  'authorId' : IDL.Text,
  'createdAt' : Time,
  'text' : IDL.Text,
  'likes' : IDL.Vec(IDL.Text),
  'imageUrl' : IDL.Opt(ExternalBlob),
  'postId' : IDL.Text,
});
export const PostView = IDL.Record({
  'id' : IDL.Text,
  'categoryId' : IDL.Text,
  'title' : IDL.Text,
  'isPublished' : IDL.Bool,
  'authorId' : IDL.Text,
  'body' : IDL.Text,
  'createdAt' : Time,
  'likes' : IDL.Vec(IDL.Text),
  'updatedAt' : Time,
  'mediaUrls' : IDL.Vec(ExternalBlob),
  'isPinned' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCategory' : IDL.Func([IDL.Text], [], []),
  'addComment' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
      [IDL.Text],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'blockUser' : IDL.Func([IDL.Text], [], []),
  'createPost' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(ExternalBlob)],
      [IDL.Text],
      [],
    ),
  'deleteAccount' : IDL.Func([], [], []),
  'deleteCategory' : IDL.Func([IDL.Text], [], []),
  'deleteComment' : IDL.Func([IDL.Text], [], []),
  'deletePost' : IDL.Func([IDL.Text], [], []),
  'editPost' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(ExternalBlob)],
      [],
      [],
    ),
  'followUser' : IDL.Func([IDL.Text], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'getCommentsForPost' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(CommentView)],
      ['query'],
    ),
  'getFollowers' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
  'getFollowing' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
  'getFollowingFeed' : IDL.Func([], [IDL.Vec(PostView)], ['query']),
  'getPost' : IDL.Func([IDL.Text], [IDL.Opt(PostView)], ['query']),
  'getPosts' : IDL.Func([], [IDL.Vec(PostView)], ['query']),
  'getPostsByAuthor' : IDL.Func([IDL.Text], [IDL.Vec(PostView)], ['query']),
  'getPostsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(PostView)], ['query']),
  'getProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getUserProfile' : IDL.Func([IDL.Text], [IDL.Opt(UserProfile)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'likeComment' : IDL.Func([IDL.Text], [], []),
  'likePost' : IDL.Func([IDL.Text], [], []),
  'listUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'login' : IDL.Func([IDL.Vec(IDL.Nat8)], [IDL.Text], []),
  'pinPost' : IDL.Func([IDL.Text], [], []),
  'publishPost' : IDL.Func([IDL.Text], [], []),
  'register' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Nat8), IDL.Vec(IDL.Nat8)],
      [IDL.Text],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'unblockUser' : IDL.Func([IDL.Text], [], []),
  'unfollowUser' : IDL.Func([IDL.Text], [], []),
  'unlikePost' : IDL.Func([IDL.Text], [], []),
  'updateUserRole' : IDL.Func([IDL.Text, BlogRole], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BlogRole = IDL.Variant({
    'moderator' : IDL.Null,
    'user' : IDL.Null,
    'superadmin' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'alias' : IDL.Text,
    'isBlocked' : IDL.Bool,
    'blogRole' : BlogRole,
  });
  const Category = IDL.Record({ 'id' : IDL.Text, 'name' : IDL.Text });
  const Time = IDL.Int;
  const CommentView = IDL.Record({
    'id' : IDL.Text,
    'authorId' : IDL.Text,
    'createdAt' : Time,
    'text' : IDL.Text,
    'likes' : IDL.Vec(IDL.Text),
    'imageUrl' : IDL.Opt(ExternalBlob),
    'postId' : IDL.Text,
  });
  const PostView = IDL.Record({
    'id' : IDL.Text,
    'categoryId' : IDL.Text,
    'title' : IDL.Text,
    'isPublished' : IDL.Bool,
    'authorId' : IDL.Text,
    'body' : IDL.Text,
    'createdAt' : Time,
    'likes' : IDL.Vec(IDL.Text),
    'updatedAt' : Time,
    'mediaUrls' : IDL.Vec(ExternalBlob),
    'isPinned' : IDL.Bool,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCategory' : IDL.Func([IDL.Text], [], []),
    'addComment' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
        [IDL.Text],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'blockUser' : IDL.Func([IDL.Text], [], []),
    'createPost' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(ExternalBlob)],
        [IDL.Text],
        [],
      ),
    'deleteAccount' : IDL.Func([], [], []),
    'deleteCategory' : IDL.Func([IDL.Text], [], []),
    'deleteComment' : IDL.Func([IDL.Text], [], []),
    'deletePost' : IDL.Func([IDL.Text], [], []),
    'editPost' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(ExternalBlob)],
        [],
        [],
      ),
    'followUser' : IDL.Func([IDL.Text], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'getCommentsForPost' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(CommentView)],
        ['query'],
      ),
    'getFollowers' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
    'getFollowing' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
    'getFollowingFeed' : IDL.Func([], [IDL.Vec(PostView)], ['query']),
    'getPost' : IDL.Func([IDL.Text], [IDL.Opt(PostView)], ['query']),
    'getPosts' : IDL.Func([], [IDL.Vec(PostView)], ['query']),
    'getPostsByAuthor' : IDL.Func([IDL.Text], [IDL.Vec(PostView)], ['query']),
    'getPostsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(PostView)], ['query']),
    'getProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getUserProfile' : IDL.Func([IDL.Text], [IDL.Opt(UserProfile)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'likeComment' : IDL.Func([IDL.Text], [], []),
    'likePost' : IDL.Func([IDL.Text], [], []),
    'listUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'login' : IDL.Func([IDL.Vec(IDL.Nat8)], [IDL.Text], []),
    'pinPost' : IDL.Func([IDL.Text], [], []),
    'publishPost' : IDL.Func([IDL.Text], [], []),
    'register' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Nat8), IDL.Vec(IDL.Nat8)],
        [IDL.Text],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'unblockUser' : IDL.Func([IDL.Text], [], []),
    'unfollowUser' : IDL.Func([IDL.Text], [], []),
    'unlikePost' : IDL.Func([IDL.Text], [], []),
    'updateUserRole' : IDL.Func([IDL.Text, BlogRole], [], []),
  });
};

export const init = ({ IDL }) => { return []; };