/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import {
  Actor,
  type ActorConfig,
  type ActorSubclass,
  type Agent,
  HttpAgent,
  type HttpAgentOptions,
} from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { type _SERVICE, idlFactory } from "./declarations/backend.did";
export interface Some<T> {
  __kind__: "Some";
  value: T;
}
export interface None {
  __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
  return {
    __kind__: "Some",
    value: value,
  };
}
function none(): None {
  return {
    __kind__: "None",
  };
}
function isNone<T>(option: Option<T>): option is None {
  return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
  return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
  if (isNone(option)) {
    throw new Error("unwrap: none");
  }
  return option.value;
}
function candid_some<T>(value: T): [T] {
  return [value];
}
function candid_none<T>(): [] {
  return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
  return arg == null ? undefined : arg;
}
export class ExternalBlob {
  _blob?: Uint8Array<ArrayBuffer> | null;
  directURL: string;
  onProgress?: (percentage: number) => void = undefined;
  private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null) {
    if (blob) {
      this._blob = blob;
    }
    this.directURL = directURL;
  }
  static fromURL(url: string): ExternalBlob {
    return new ExternalBlob(url, null);
  }
  static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
    const url = URL.createObjectURL(
      new Blob([new Uint8Array(blob)], {
        type: "application/octet-stream",
      }),
    );
    return new ExternalBlob(url, blob);
  }
  public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
    if (this._blob) {
      return this._blob;
    }
    const response = await fetch(this.directURL);
    const blob = await response.blob();
    this._blob = new Uint8Array(await blob.arrayBuffer());
    return this._blob;
  }
  public getDirectURL(): string {
    return this.directURL;
  }
  public withUploadProgress(
    onProgress: (percentage: number) => void,
  ): ExternalBlob {
    this.onProgress = onProgress;
    return this;
  }
}
export interface Category {
  id: string;
  name: string;
  isHidden: boolean;
}
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
  proposed_top_up_amount?: bigint;
}
export interface PostView {
  id: string;
  categoryId: string;
  title: string;
  isPublished: boolean;
  authorId: string;
  body: string;
  createdAt: Time;
  likes: Array<string>;
  updatedAt: Time;
  mediaUrls: Array<ExternalBlob>;
  isPinned: boolean;
}
export interface _CaffeineStorageCreateCertificateResult {
  method: string;
  blob_hash: string;
}
export interface CommentView {
  id: string;
  authorId: string;
  createdAt: Time;
  text: string;
  likes: Array<string>;
  imageUrl?: ExternalBlob;
  postId: string;
}
export interface UserProfile {
  alias: string;
  isBlocked: boolean;
  blogRole: BlogRole;
}
export interface _CaffeineStorageRefillResult {
  success?: boolean;
  topped_up_amount?: bigint;
}
export enum BlogRole {
  moderator = "moderator",
  user = "user",
  superadmin = "superadmin",
}
export enum UserRole {
  admin = "admin",
  user = "user",
  guest = "guest",
}
export interface backendInterface {
  _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
  _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
  _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
  _caffeineStorageCreateCertificate(
    blobHash: string,
  ): Promise<_CaffeineStorageCreateCertificateResult>;
  _caffeineStorageRefillCashier(
    refillInformation: _CaffeineStorageRefillInformation | null,
  ): Promise<_CaffeineStorageRefillResult>;
  _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
  _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
  addCategory(name: string, isHidden: boolean): Promise<void>;
  getCategoryPermissions(
    categoryId: string,
  ): Promise<{ readAllowlist: Array<string>; commentAllowlist: Array<string> }>;
  setCategoryPermissions(
    categoryId: string,
    readAllowlist: Array<string>,
    commentAllowlist: Array<string>,
  ): Promise<void>;
  setCategoryVisibility(categoryId: string, isHidden: boolean): Promise<void>;
  addComment(
    postId: string,
    text: string,
    imageUrl: ExternalBlob | null,
  ): Promise<string>;
  assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
  blockUser(userId: string): Promise<void>;
  createPost(
    title: string,
    body: string,
    categoryId: string,
    mediaUrls: Array<ExternalBlob>,
  ): Promise<string>;
  deleteAccount(): Promise<void>;
  deleteCategory(categoryId: string): Promise<void>;
  deleteComment(commentId: string): Promise<void>;
  deletePost(postId: string): Promise<void>;
  editPost(
    postId: string,
    title: string,
    body: string,
    categoryId: string,
    mediaUrls: Array<ExternalBlob>,
  ): Promise<void>;
  followUser(targetUserId: string): Promise<void>;
  getCallerUserProfile(): Promise<UserProfile | null>;
  getCallerUserRole(): Promise<UserRole>;
  getCategories(): Promise<Array<Category>>;
  getCommentsForPost(postId: string): Promise<Array<CommentView>>;
  getFollowers(userId: string): Promise<Array<string>>;
  getFollowing(userId: string): Promise<Array<string>>;
  getFollowingFeed(): Promise<Array<PostView>>;
  getPost(postId: string): Promise<PostView | null>;
  getPosts(): Promise<Array<PostView>>;
  getPostsByAuthor(authorId: string): Promise<Array<PostView>>;
  getPostsByCategory(categoryId: string): Promise<Array<PostView>>;
  getProfile(): Promise<UserProfile | null>;
  getUserProfile(userId: string): Promise<UserProfile | null>;
  isCallerAdmin(): Promise<boolean>;
  likeComment(commentId: string): Promise<void>;
  likePost(postId: string): Promise<void>;
  listUsers(): Promise<Array<UserProfile>>;
  login(passwordHash: Uint8Array): Promise<string>;
  pinPost(postId: string): Promise<void>;
  publishPost(postId: string): Promise<void>;
  register(
    alias: string,
    passwordHash: Uint8Array,
    salt: Uint8Array,
  ): Promise<string>;
  saveCallerUserProfile(profile: UserProfile): Promise<void>;
  unblockUser(userId: string): Promise<void>;
  unfollowUser(targetUserId: string): Promise<void>;
  unlikePost(postId: string): Promise<void>;
  updateUserRole(userId: string, newRole: BlogRole): Promise<void>;
}

import type {
  _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation,
  _CaffeineStorageRefillResult as __CaffeineStorageRefillResult,
  BlogRole as _BlogRole,
  CommentView as _CommentView,
  ExternalBlob as _ExternalBlob,
  PostView as _PostView,
  Time as _Time,
  UserProfile as _UserProfile,
  UserRole as _UserRole,
} from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
  constructor(
    private actor: ActorSubclass<_SERVICE>,
    private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>,
    private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>,
    private processError?: (error: unknown) => never,
  ) {}
  async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
    if (this.processError) {
      try {
        const result = await this.actor._caffeineStorageBlobIsLive(arg0);
        return result;
      } catch (e) {
        this.processError(e);
        throw new Error("unreachable");
      }
    } else {
      const result = await this.actor._caffeineStorageBlobIsLive(arg0);
      return result;
    }
  }
  async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
    if (this.processError) {
      try {
        const result = await this.actor._caffeineStorageBlobsToDelete();
        return result;
      } catch (e) {
        this.processError(e);
        throw new Error("unreachable");
      }
    } else {
      const result = await this.actor._caffeineStorageBlobsToDelete();
      return result;
    }
  }
  async _caffeineStorageConfirmBlobDeletion(
    arg0: Array<Uint8Array>,
  ): Promise<void> {
    if (this.processError) {
      try {
        const result =
          await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
        return result;
      } catch (e) {
        this.processError(e);
        throw new Error("unreachable");
      }
    } else {
      const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
      return result;
    }
  }
  async _caffeineStorageCreateCertificate(
    arg0: string,
  ): Promise<_CaffeineStorageCreateCertificateResult> {
    if (this.processError) {
      try {
        const result = await this.actor._caffeineStorageCreateCertificate(arg0);
        return result;
      } catch (e) {
        this.processError(e);
        throw new Error("unreachable");
      }
    } else {
      const result = await this.actor._caffeineStorageCreateCertificate(arg0);
      return result;
    }
  }
  async _caffeineStorageRefillCashier(
    arg0: _CaffeineStorageRefillInformation | null,
  ): Promise<_CaffeineStorageRefillResult> {
    if (this.processError) {
      try {
        const result = await this.actor._caffeineStorageRefillCashier(
          to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0),
        );
        return from_candid__CaffeineStorageRefillResult_n4(
          this._uploadFile,
          this._downloadFile,
          result,
        );
      } catch (e) {
        this.processError(e);
        throw new Error("unreachable");
      }
    } else {
      const result = await this.actor._caffeineStorageRefillCashier(
        to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0),
      );
      return from_candid__CaffeineStorageRefillResult_n4(
        this._uploadFile,
        this._downloadFile,
        result,
      );
    }
  }
  async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
    if (this.processError) {
      try {
        const result =
          await this.actor._caffeineStorageUpdateGatewayPrincipals();
        return result;
      } catch (e) {
        this.processError(e);
        throw new Error("unreachable");
      }
    } else {
      const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
      return result;
    }
  }
  async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
    if (this.processError) {
      try {
        const result =
          await this.actor._initializeAccessControlWithSecret(arg0);
        return result;
      } catch (e) {
        this.processError(e);
        throw new Error("unreachable");
      }
    } else {
      const result = await this.actor._initializeAccessControlWithSecret(arg0);
      return result;
    }
  }
  async addCategory(arg0: string, arg1: boolean): Promise<void> {
    if (this.processError) {
      try {
        const result = await this.actor.addCategory(arg0, arg1);
        return result;
      } catch (e) {
        this.processError(e);
        throw new Error("unreachable");
      }
    } else {
      const result = await this.actor.addCategory(arg0, arg1);
      return result;
    }
  }
  async getCategoryPermissions(arg0: string): Promise<{
    readAllowlist: Array<string>;
    commentAllowlist: Array<string>;
  }> {
    if (this.processError) {
      try {
        const result = await (this.actor as any).getCategoryPermissions(arg0);
        return result;
      } catch (e) {
        this.processError(e);
        throw new Error("unreachable");
      }
    } else {
      return (this.actor as any).getCategoryPermissions(arg0);
    }
  }
  async setCategoryPermissions(
    arg0: string,
    arg1: Array<string>,
    arg2: Array<string>,
  ): Promise<void> {
    if (this.processError) {
      try {
        await (this.actor as any).setCategoryPermissions(arg0, arg1, arg2);
      } catch (e) {
        this.processError(e);
        throw new Error("unreachable");
      }
    } else {
      await (this.actor as any).setCategoryPermissions(arg0, arg1, arg2);
    }
  }
  async setCategoryVisibility(arg0: string, arg1: boolean): Promise<void> {
    if (this.processError) {
      try {
        await (this.actor as any).setCategoryVisibility(arg0, arg1);
      } catch (e) {
        this.processError(e);
        throw new Error("unreachable");
      }
    } else {
      await (this.actor as any).setCategoryVisibility(arg0, arg1);
    }
  }
  async addComment(
    arg0: string,
    arg1: string,
    arg2: ExternalBlob | null,
  ): Promise<string> {
    if (this.processError) {
      try {
        const result = await this.actor.addComment(
          arg0,
          arg1,
          await to_candid_opt_n8(this._uploadFile, this._downloadFile, arg2),
        );
        return result;
      } catch (e) {
        this.processError(e);
        throw new Error("unreachable");
      }
    } else {
      const result = await this.actor.addComment(
        arg0,
        arg1,
        await to_candid_opt_n8(this._uploadFile, this._downloadFile, arg2),
      );
      return result;
    }
  }
  async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
    if (this.processError) {
      try {
        const result = await this.actor.assignCallerUserRole(
          arg0,
          to_candid_UserRole_n10(this._uploadFile, this._downloadFile, arg1),
        );
        return result;
      } catch (e) {
        this.processError(e);
        throw new Error("unreachable");
      }
    } else {
      const result = await this.actor.assignCallerUserRole(
        arg0,
        to_candid_UserRole_n10(this._uploadFile, this._downloadFile, arg1),
      );
      return result;
    }
  }
  async blockUser(arg0: string): Promise<void> {
    if (this.processError) {
      try {
        const result = await this.actor.blockUser(arg0);
        return result;
      } catch (e) {
        this.processError(e);
        throw new Error("unreachable");
      }
    } else {
      const result = await this.actor.blockUser(arg0);
      return result;
    }
  }
  async createPost(
    arg0: string,
    arg1: string,
    arg2: string,
    arg3: Array<ExternalBlob>,
  ): Promise<string> {
    if (this.processError) {
      try {
        const result = await this.actor.createPost(
          arg0,
          arg1,
          arg2,
          await to_candid_vec_n12(this._uploadFile, this._downloadFile, arg3),
        );
        return result;
      } catch (e) {
        this.processError(e);
        throw new Error("unreachable");
      }
    } else {
      const result = await this.actor.createPost(
        arg0,
        arg1,
        arg2,
        await to_candid_vec_n12(this._uploadFile, this._downloadFile, arg3),
      );
      return result;
    }
  }
  async deleteAccount(): Promise<void> {
    if (this.processError) {
      try {
        const result = await this.actor.deleteAccount();
        return result;
      } catch (e) {
        this.processError(e);
        throw new Error("unreachable");
      }
    } else {
      const result = await this.actor.deleteAccount();
      return result;
    }
  }
  async deleteCategory(arg0: string): Promise<void> {
    if (this.processError) {
      try {
        const result = await this.actor.deleteCategory(arg0);
        return result;
      } catch (e) {
        this.processError(e);
        throw new Error("unreachable");
      }
    } else {
      const result = await this.actor.deleteCategory(arg0);
      return result;
    }
  }
  async deleteComment(arg0: string): Promise<void> {
    if (this.processError) {
      try {
        const result = await this.actor.deleteComment(arg0);
        return result;
      } catch (e) {
        this.processError(e);
        throw new Error("unreachable");
      }
    } else {
      const result = await this.actor.deleteComment(arg0);
      return result;
    }
  }
  async deletePost(arg0: string): Promise<void> {
    if (this.processError) {
      try {
        const result = await this.actor.deletePost(arg0);
        return result;
      } catch (e) {
        this.processError(e);
        throw new Error("unreachable");
      }
    } else {
      const result = await this.actor.deletePost(arg0);
      return result;
    }
  }
  async editPost(
    arg0: string,
    arg1: string,
    arg2: string,
    arg3: string,
    arg4: Array<ExternalBlob>,
  ): Promise<void> {
    if (this.processError) {
      try {
        const result = await this.actor.editPost(
          arg0,
          arg1,
          arg2,
          arg3,
          await to_candid_vec_n12(this._uploadFile, this._downloadFile, arg4),
        );
        return result;
      } catch (e) {
        this.processError(e);
        throw new Error("unreachable");
      }
    } else {
      const result = await this.actor.editPost(
        arg0,
        arg1,
        arg2,
        arg3,
        await to_candid_vec_n12(this._uploadFile, this._downloadFile, arg4),
      );
      return result;
    }
  }
  async followUser(arg0: string): Promise<void> {
    if (this.processError) {
      try {
        const result = await this.actor.followUser(arg0);
        return result;
      } catch (e) {
        this.processError(e);
        throw new Error("unreachable");
      }
    } else {
      const result = await this.actor.followUser(arg0);
      return result;
    }
  }
  async getCallerUserProfile(): Promise<UserProfile | null> {
    if (this.processError) {
      try {
        const result = await this.actor.getCallerUserProfile();
        return from_candid_opt_n13(
          this._uploadFile,
          this._downloadFile,
          result,
        );
      } catch (e) {
        this.processError(e);
        throw new Error("unreachable");
      }
    } else {
      const result = await this.actor.getCallerUserProfile();
      return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
    }
  }
  async getCallerUserRole(): Promise<UserRole> {
    if (this.processError) {
      try {
        const result = await this.actor.getCallerUserRole();
        return from_candid_UserRole_n18(
          this._uploadFile,
          this._downloadFile,
          result,
        );
      } catch (e) {
        this.processError(e);
        throw new Error("unreachable");
      }
    } else {
      const result = await this.actor.getCallerUserRole();
      return from_candid_UserRole_n18(
        this._uploadFile,
        this._downloadFile,
        result,
      );
    }
  }
  async getCategories(): Promise<Array<Category>> {
    if (this.processError) {
      try {
        const result = await this.actor.getCategories();
        return result;
      } catch (e) {
        this.processError(e);
        throw new Error("unreachable");
      }
    } else {
      const result = await this.actor.getCategories();
      return result;
    }
  }
  async getCommentsForPost(arg0: string): Promise<Array<CommentView>> {
    if (this.processError) {
      try {
        const result = await this.actor.getCommentsForPost(arg0);
        return from_candid_vec_n20(
          this._uploadFile,
          this._downloadFile,
          result,
        );
      } catch (e) {
        this.processError(e);
        throw new Error("unreachable");
      }
    } else {
      const result = await this.actor.getCommentsForPost(arg0);
      return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
    }
  }
  async getFollowers(arg0: string): Promise<Array<string>> {
    if (this.processError) {
      try {
        const result = await this.actor.getFollowers(arg0);
        return result;
      } catch (e) {
        this.processError(e);
        throw new Error("unreachable");
      }
    } else {
      const result = await this.actor.getFollowers(arg0);
      return result;
    }
  }
  async getFollowing(arg0: string): Promise<Array<string>> {
    if (this.processError) {
      try {
        const result = await this.actor.getFollowing(arg0);
        return result;
      } catch (e) {
        this.processError(e);
        throw new Error("unreachable");
      }
    } else {
      const result = await this.actor.getFollowing(arg0);
      return result;
    }
  }
  async getFollowingFeed(): Promise<Array<PostView>> {
    if (this.processError) {
      try {
        const result = await this.actor.getFollowingFeed();
        return from_candid_vec_n25(
          this._uploadFile,
          this._downloadFile,
          result,
        );
      } catch (e) {
        this.processError(e);
        throw new Error("unreachable");
      }
    } else {
      const result = await this.actor.getFollowingFeed();
      return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
    }
  }
  async getPost(arg0: string): Promise<PostView | null> {
    if (this.processError) {
      try {
        const result = await this.actor.getPost(arg0);
        return from_candid_opt_n29(
          this._uploadFile,
          this._downloadFile,
          result,
        );
      } catch (e) {
        this.processError(e);
        throw new Error("unreachable");
      }
    } else {
      const result = await this.actor.getPost(arg0);
      return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
    }
  }
  async getPosts(): Promise<Array<PostView>> {
    if (this.processError) {
      try {
        const result = await this.actor.getPosts();
        return from_candid_vec_n25(
          this._uploadFile,
          this._downloadFile,
          result,
        );
      } catch (e) {
        this.processError(e);
        throw new Error("unreachable");
      }
    } else {
      const result = await this.actor.getPosts();
      return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
    }
  }
  async getPostsByAuthor(arg0: string): Promise<Array<PostView>> {
    if (this.processError) {
      try {
        const result = await this.actor.getPostsByAuthor(arg0);
        return from_candid_vec_n25(
          this._uploadFile,
          this._downloadFile,
          result,
        );
      } catch (e) {
        this.processError(e);
        throw new Error("unreachable");
      }
    } else {
      const result = await this.actor.getPostsByAuthor(arg0);
      return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
    }
  }
  async getPostsByCategory(arg0: string): Promise<Array<PostView>> {
    if (this.processError) {
      try {
        const result = await this.actor.getPostsByCategory(arg0);
        return from_candid_vec_n25(
          this._uploadFile,
          this._downloadFile,
          result,
        );
      } catch (e) {
        this.processError(e);
        throw new Error("unreachable");
      }
    } else {
      const result = await this.actor.getPostsByCategory(arg0);
      return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
    }
  }
  async getProfile(): Promise<UserProfile | null> {
    if (this.processError) {
      try {
        const result = await this.actor.getProfile();
        return from_candid_opt_n13(
          this._uploadFile,
          this._downloadFile,
          result,
        );
      } catch (e) {
        this.processError(e);
        throw new Error("unreachable");
      }
    } else {
      const result = await this.actor.getProfile();
      return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
    }
  }
  async getUserProfile(arg0: string): Promise<UserProfile | null> {
    if (this.processError) {
      try {
        const result = await this.actor.getUserProfile(arg0);
        return from_candid_opt_n13(
          this._uploadFile,
          this._downloadFile,
          result,
        );
      } catch (e) {
        this.processError(e);
        throw new Error("unreachable");
      }
    } else {
      const result = await this.actor.getUserProfile(arg0);
      return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
    }
  }
  async isCallerAdmin(): Promise<boolean> {
    if (this.processError) {
      try {
        const result = await this.actor.isCallerAdmin();
        return result;
      } catch (e) {
        this.processError(e);
        throw new Error("unreachable");
      }
    } else {
      const result = await this.actor.isCallerAdmin();
      return result;
    }
  }
  async likeComment(arg0: string): Promise<void> {
    if (this.processError) {
      try {
        const result = await this.actor.likeComment(arg0);
        return result;
      } catch (e) {
        this.processError(e);
        throw new Error("unreachable");
      }
    } else {
      const result = await this.actor.likeComment(arg0);
      return result;
    }
  }
  async likePost(arg0: string): Promise<void> {
    if (this.processError) {
      try {
        const result = await this.actor.likePost(arg0);
        return result;
      } catch (e) {
        this.processError(e);
        throw new Error("unreachable");
      }
    } else {
      const result = await this.actor.likePost(arg0);
      return result;
    }
  }
  async listUsers(): Promise<Array<UserProfile>> {
    if (this.processError) {
      try {
        const result = await this.actor.listUsers();
        return from_candid_vec_n30(
          this._uploadFile,
          this._downloadFile,
          result,
        );
      } catch (e) {
        this.processError(e);
        throw new Error("unreachable");
      }
    } else {
      const result = await this.actor.listUsers();
      return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
    }
  }
  async login(arg0: Uint8Array): Promise<string> {
    if (this.processError) {
      try {
        const result = await this.actor.login(arg0);
        return result;
      } catch (e) {
        this.processError(e);
        throw new Error("unreachable");
      }
    } else {
      const result = await this.actor.login(arg0);
      return result;
    }
  }
  async pinPost(arg0: string): Promise<void> {
    if (this.processError) {
      try {
        const result = await this.actor.pinPost(arg0);
        return result;
      } catch (e) {
        this.processError(e);
        throw new Error("unreachable");
      }
    } else {
      const result = await this.actor.pinPost(arg0);
      return result;
    }
  }
  async publishPost(arg0: string): Promise<void> {
    if (this.processError) {
      try {
        const result = await this.actor.publishPost(arg0);
        return result;
      } catch (e) {
        this.processError(e);
        throw new Error("unreachable");
      }
    } else {
      const result = await this.actor.publishPost(arg0);
      return result;
    }
  }
  async register(
    arg0: string,
    arg1: Uint8Array,
    arg2: Uint8Array,
  ): Promise<string> {
    if (this.processError) {
      try {
        const result = await this.actor.register(arg0, arg1, arg2);
        return result;
      } catch (e) {
        this.processError(e);
        throw new Error("unreachable");
      }
    } else {
      const result = await this.actor.register(arg0, arg1, arg2);
      return result;
    }
  }
  async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
    if (this.processError) {
      try {
        const result = await this.actor.saveCallerUserProfile(
          to_candid_UserProfile_n31(this._uploadFile, this._downloadFile, arg0),
        );
        return result;
      } catch (e) {
        this.processError(e);
        throw new Error("unreachable");
      }
    } else {
      const result = await this.actor.saveCallerUserProfile(
        to_candid_UserProfile_n31(this._uploadFile, this._downloadFile, arg0),
      );
      return result;
    }
  }
  async unblockUser(arg0: string): Promise<void> {
    if (this.processError) {
      try {
        const result = await this.actor.unblockUser(arg0);
        return result;
      } catch (e) {
        this.processError(e);
        throw new Error("unreachable");
      }
    } else {
      const result = await this.actor.unblockUser(arg0);
      return result;
    }
  }
  async unfollowUser(arg0: string): Promise<void> {
    if (this.processError) {
      try {
        const result = await this.actor.unfollowUser(arg0);
        return result;
      } catch (e) {
        this.processError(e);
        throw new Error("unreachable");
      }
    } else {
      const result = await this.actor.unfollowUser(arg0);
      return result;
    }
  }
  async unlikePost(arg0: string): Promise<void> {
    if (this.processError) {
      try {
        const result = await this.actor.unlikePost(arg0);
        return result;
      } catch (e) {
        this.processError(e);
        throw new Error("unreachable");
      }
    } else {
      const result = await this.actor.unlikePost(arg0);
      return result;
    }
  }
  async updateUserRole(arg0: string, arg1: BlogRole): Promise<void> {
    if (this.processError) {
      try {
        const result = await this.actor.updateUserRole(
          arg0,
          to_candid_BlogRole_n33(this._uploadFile, this._downloadFile, arg1),
        );
        return result;
      } catch (e) {
        this.processError(e);
        throw new Error("unreachable");
      }
    } else {
      const result = await this.actor.updateUserRole(
        arg0,
        to_candid_BlogRole_n33(this._uploadFile, this._downloadFile, arg1),
      );
      return result;
    }
  }
}
function from_candid_BlogRole_n16(
  _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>,
  _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>,
  value: _BlogRole,
): BlogRole {
  return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
async function from_candid_CommentView_n21(
  _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>,
  _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>,
  value: _CommentView,
): Promise<CommentView> {
  return await from_candid_record_n22(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n24(
  _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>,
  _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>,
  value: _ExternalBlob,
): Promise<ExternalBlob> {
  return await _downloadFile(value);
}
async function from_candid_PostView_n26(
  _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>,
  _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>,
  value: _PostView,
): Promise<PostView> {
  return await from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n14(
  _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>,
  _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>,
  value: _UserProfile,
): UserProfile {
  return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n18(
  _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>,
  _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>,
  value: _UserRole,
): UserRole {
  return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(
  _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>,
  _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>,
  value: __CaffeineStorageRefillResult,
): _CaffeineStorageRefillResult {
  return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(
  _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>,
  _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>,
  value: [] | [_UserProfile],
): UserProfile | null {
  return value.length === 0
    ? null
    : from_candid_UserProfile_n14(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n23(
  _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>,
  _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>,
  value: [] | [_ExternalBlob],
): Promise<ExternalBlob | null> {
  return value.length === 0
    ? null
    : await from_candid_ExternalBlob_n24(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n29(
  _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>,
  _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>,
  value: [] | [_PostView],
): Promise<PostView | null> {
  return value.length === 0
    ? null
    : await from_candid_PostView_n26(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(
  _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>,
  _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>,
  value: [] | [boolean],
): boolean | null {
  return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(
  _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>,
  _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>,
  value: [] | [bigint],
): bigint | null {
  return value.length === 0 ? null : value[0];
}
function from_candid_record_n15(
  _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>,
  _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>,
  value: {
    alias: string;
    isBlocked: boolean;
    blogRole: _BlogRole;
  },
): {
  alias: string;
  isBlocked: boolean;
  blogRole: BlogRole;
} {
  return {
    alias: value.alias,
    isBlocked: value.isBlocked,
    blogRole: from_candid_BlogRole_n16(
      _uploadFile,
      _downloadFile,
      value.blogRole,
    ),
  };
}
async function from_candid_record_n22(
  _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>,
  _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>,
  value: {
    id: string;
    authorId: string;
    createdAt: _Time;
    text: string;
    likes: Array<string>;
    imageUrl: [] | [_ExternalBlob];
    postId: string;
  },
): Promise<{
  id: string;
  authorId: string;
  createdAt: Time;
  text: string;
  likes: Array<string>;
  imageUrl?: ExternalBlob;
  postId: string;
}> {
  return {
    id: value.id,
    authorId: value.authorId,
    createdAt: value.createdAt,
    text: value.text,
    likes: value.likes,
    imageUrl: record_opt_to_undefined(
      await from_candid_opt_n23(_uploadFile, _downloadFile, value.imageUrl),
    ),
    postId: value.postId,
  };
}
async function from_candid_record_n27(
  _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>,
  _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>,
  value: {
    id: string;
    categoryId: string;
    title: string;
    isPublished: boolean;
    authorId: string;
    body: string;
    createdAt: _Time;
    likes: Array<string>;
    updatedAt: _Time;
    mediaUrls: Array<_ExternalBlob>;
    isPinned: boolean;
  },
): Promise<{
  id: string;
  categoryId: string;
  title: string;
  isPublished: boolean;
  authorId: string;
  body: string;
  createdAt: Time;
  likes: Array<string>;
  updatedAt: Time;
  mediaUrls: Array<ExternalBlob>;
  isPinned: boolean;
}> {
  return {
    id: value.id,
    categoryId: value.categoryId,
    title: value.title,
    isPublished: value.isPublished,
    authorId: value.authorId,
    body: value.body,
    createdAt: value.createdAt,
    likes: value.likes,
    updatedAt: value.updatedAt,
    mediaUrls: await from_candid_vec_n28(
      _uploadFile,
      _downloadFile,
      value.mediaUrls,
    ),
    isPinned: value.isPinned,
  };
}
function from_candid_record_n5(
  _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>,
  _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>,
  value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
  },
): {
  success?: boolean;
  topped_up_amount?: bigint;
} {
  return {
    success: record_opt_to_undefined(
      from_candid_opt_n6(_uploadFile, _downloadFile, value.success),
    ),
    topped_up_amount: record_opt_to_undefined(
      from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount),
    ),
  };
}
function from_candid_variant_n17(
  _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>,
  _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>,
  value:
    | {
        moderator: null;
      }
    | {
        user: null;
      }
    | {
        superadmin: null;
      },
): BlogRole {
  return "moderator" in value
    ? BlogRole.moderator
    : "user" in value
      ? BlogRole.user
      : "superadmin" in value
        ? BlogRole.superadmin
        : value;
}
function from_candid_variant_n19(
  _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>,
  _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>,
  value:
    | {
        admin: null;
      }
    | {
        user: null;
      }
    | {
        guest: null;
      },
): UserRole {
  return "admin" in value
    ? UserRole.admin
    : "user" in value
      ? UserRole.user
      : "guest" in value
        ? UserRole.guest
        : value;
}
async function from_candid_vec_n20(
  _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>,
  _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>,
  value: Array<_CommentView>,
): Promise<Array<CommentView>> {
  return await Promise.all(
    value.map(
      async (x) =>
        await from_candid_CommentView_n21(_uploadFile, _downloadFile, x),
    ),
  );
}
async function from_candid_vec_n25(
  _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>,
  _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>,
  value: Array<_PostView>,
): Promise<Array<PostView>> {
  return await Promise.all(
    value.map(
      async (x) =>
        await from_candid_PostView_n26(_uploadFile, _downloadFile, x),
    ),
  );
}
async function from_candid_vec_n28(
  _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>,
  _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>,
  value: Array<_ExternalBlob>,
): Promise<Array<ExternalBlob>> {
  return await Promise.all(
    value.map(
      async (x) =>
        await from_candid_ExternalBlob_n24(_uploadFile, _downloadFile, x),
    ),
  );
}
function from_candid_vec_n30(
  _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>,
  _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>,
  value: Array<_UserProfile>,
): Array<UserProfile> {
  return value.map((x) =>
    from_candid_UserProfile_n14(_uploadFile, _downloadFile, x),
  );
}
function to_candid_BlogRole_n33(
  _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>,
  _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>,
  value: BlogRole,
): _BlogRole {
  return to_candid_variant_n34(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n9(
  _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>,
  _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>,
  value: ExternalBlob,
): Promise<_ExternalBlob> {
  return await _uploadFile(value);
}
function to_candid_UserProfile_n31(
  _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>,
  _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>,
  value: UserProfile,
): _UserProfile {
  return to_candid_record_n32(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n10(
  _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>,
  _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>,
  value: UserRole,
): _UserRole {
  return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(
  _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>,
  _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>,
  value: _CaffeineStorageRefillInformation,
): __CaffeineStorageRefillInformation {
  return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(
  _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>,
  _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>,
  value: _CaffeineStorageRefillInformation | null,
): [] | [__CaffeineStorageRefillInformation] {
  return value === null
    ? candid_none()
    : candid_some(
        to_candid__CaffeineStorageRefillInformation_n2(
          _uploadFile,
          _downloadFile,
          value,
        ),
      );
}
async function to_candid_opt_n8(
  _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>,
  _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>,
  value: ExternalBlob | null,
): Promise<[] | [_ExternalBlob]> {
  return value === null
    ? candid_none()
    : candid_some(
        await to_candid_ExternalBlob_n9(_uploadFile, _downloadFile, value),
      );
}
function to_candid_record_n3(
  _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>,
  _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>,
  value: {
    proposed_top_up_amount?: bigint;
  },
): {
  proposed_top_up_amount: [] | [bigint];
} {
  return {
    proposed_top_up_amount: value.proposed_top_up_amount
      ? candid_some(value.proposed_top_up_amount)
      : candid_none(),
  };
}
function to_candid_record_n32(
  _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>,
  _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>,
  value: {
    alias: string;
    isBlocked: boolean;
    blogRole: BlogRole;
  },
): {
  alias: string;
  isBlocked: boolean;
  blogRole: _BlogRole;
} {
  return {
    alias: value.alias,
    isBlocked: value.isBlocked,
    blogRole: to_candid_BlogRole_n33(
      _uploadFile,
      _downloadFile,
      value.blogRole,
    ),
  };
}
function to_candid_variant_n11(
  _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>,
  _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>,
  value: UserRole,
):
  | {
      admin: null;
    }
  | {
      user: null;
    }
  | {
      guest: null;
    } {
  return value == UserRole.admin
    ? {
        admin: null,
      }
    : value == UserRole.user
      ? {
          user: null,
        }
      : value == UserRole.guest
        ? {
            guest: null,
          }
        : value;
}
function to_candid_variant_n34(
  _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>,
  _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>,
  value: BlogRole,
):
  | {
      moderator: null;
    }
  | {
      user: null;
    }
  | {
      superadmin: null;
    } {
  return value == BlogRole.moderator
    ? {
        moderator: null,
      }
    : value == BlogRole.user
      ? {
          user: null,
        }
      : value == BlogRole.superadmin
        ? {
            superadmin: null,
          }
        : value;
}
async function to_candid_vec_n12(
  _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>,
  _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>,
  value: Array<ExternalBlob>,
): Promise<Array<_ExternalBlob>> {
  return await Promise.all(
    value.map(
      async (x) =>
        await to_candid_ExternalBlob_n9(_uploadFile, _downloadFile, x),
    ),
  );
}
export interface CreateActorOptions {
  agent?: Agent;
  agentOptions?: HttpAgentOptions;
  actorOptions?: ActorConfig;
  processError?: (error: unknown) => never;
}
export function createActor(
  canisterId: string,
  _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>,
  _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>,
  options: CreateActorOptions = {},
): Backend {
  const agent =
    options.agent ||
    HttpAgent.createSync({
      ...options.agentOptions,
    });
  if (options.agent && options.agentOptions) {
    console.warn(
      "Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.",
    );
  }
  const actor = Actor.createActor<_SERVICE>(idlFactory, {
    agent,
    canisterId: canisterId,
    ...options.actorOptions,
  });
  return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
